import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Rick and Morty',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex min-h-screen flex-col items-center justify-start pt-8 px-5 sm:px-[210px] md:px-[90px]">
          {children}
        </div>
      </body>
    </html>
  )
}
